#+TITLE: Backlog for *xoutil* - a collection of disparate utilities
#+AUTHOR: Merchise Autrement [~ยบ/~]
#+DESCRIPTION: Development planning for this package.

* Backlog for *xoutil*

** Development ideas. [/]

- [ ] Refactor CLI.

  See IPython's [[file:~/.local/lib/python2.7/site-packages/IPython/terminal/ipapp.py::addflag%20%3D%20lambda%20*args:%20frontend_flags.update(boolean_flag(*args))][addflag]].  Migrate the logic for sub-commands in 'argparse' by
  using [[file:/usr/share/doc/python/html/library/argparse.html?highlight%3Dargumentparser#argparse.ArgumentParser.add_subparsers][add_subparsers]] when definie method [[file:xoutil/cli/__init__.py::def%20get_arg_parser(cls):][get_arg_parser]] for sub-classes of
  [[file:xoutil/cli/__init__.py::class%20Command(ABC):][xoutil.cli.Command]].

** Miscellaneous. [/]

   - [ ] Add Python 3 'partialmethod' into 'xoutil.future.functools' (or maybe
     into 'xoutil.eight').

  - [ ] Review and fix 'xoutil.decorator' module.  Get ideas from
    [[https://github.com/dbrattli/OSlash/blob/master/oslash/util/extensionmethod.py][extensionmethod]] from OSlash in order to improve our module.

  - [ ] Review [[https://github.com/dbrattli/OSlash/blob/master/oslash/util/fn.py][fn]] from OSlash, generalize and integrate our 'compose' versions
    in 'xoutil.future.functools' and 'xoutil.cl' using their ideas.

  - Implement Python 3 'functools.singledispatch' in our
    'xoutil.future.functools'. Ask @manu for an equivalent tool he programmed.
    Use a similar mechanism also in 'xoutil.fp' for pattern matching.


** Develop Monad concept into 'xoutil'. [/]

   There are several "old" modules that could be migrated (or integrated) into
   new monads modules; these old modules could become clients of monads.

   - [ ] 'xoutil.connote': intends for to have predicates (commonly understood
     to be Boolean-valued functions).

   - [ ] 'xoutil.symbols': to be instance of and sub-class checks in
     'MetaSymbol' class must be extended to be compliant with monads.

   - [ ] 'xoutil.cl': reproducing some concepts of "Common Lisp" in Python.
     Value checkers are the best candidates to be monadic.

   - [ ] 'xoutil.values': this module is deprecated but must be analyzed
     during this proccess.


** Errors

- [ ] Fix IPython "recursive reload" in all xoutil modules for all Python
  versions.

  The =IPython.lib.deepreload= module allows you to recursively reload a
  module: changes made to any of its dependencies will be reloaded without
  having to exit.

  When it is run on =xoutil=:

  #+begin_src python
    from IPython.lib.deepreload import reload as dreload
    import xoutil
    dreload(xoutil)
  #+end_src

** Configuration. [/]
